#ifndef COMPOSER_CONSTS_H
#define COMPOSER_CONSTS_H

#define ROCC_CMD_ACCEL 0x7b
#define ROCC_CMD_FLUSH 0xb

#define RESP_BITS 0 //READONLY
#define RESP_VALID 1 //READONLY
#define RESP_READY 2 //WRITEONLY

#define CMD_BITS 3 //WRITEONLY
#define CMD_VALID 4 //WRITEONLY
#define CMD_READY 5 //READONLY

#define NUM_ITERATIONS 12
#define N_COLS_TO_PASS 1
#define NUM_BUFFERS 2

#define MAX_KEY_BYTES 8
#define MAX_COL_BYTES 32

#define MAX_COLUMNS 3
#define MAX_PART_KEYS 1
#define MAX_SORT_KEYS 1

#define NUM_PARTERS 1
#define MAX_PARTITIONS 8
#define MAX_SPLITTERS 7
#define MAX_PART_ELEMS 1024
#define MAX_FINAL_PART_ELEMS 8192

#define NUM_SORTERS 7
#define MAX_SORT_ELEMS 1024

#define MAX_AGGERS 7
#define MAX_AGG_ELEMS 1024
#define NUM_AGG_GROUP 1
#define NUM_AGG_KEY 1
#define MAX_AGG_AUX 2

#define NUM_REDUCERS 1
#define NUM_REDUCE_COL 1

#define INIT_ADDR 0x0
#define BUFFER_SIZE 250
#define BITS_PER_CACHE_LINE 1024
#define BITS_PER_BYTE 8

#define DMA_BLOCK_SIZE 16777216

#define WRITE_BITS 6 //WRITEONLY
#define WRITE_VALID 7 //WRITEONLY
#define WRITE_READY 8 //READONLY

#define READ_ADDR_BITS 9 //WRITEONLY
#define READ_ADDR_VALID 10 //WRITEONLY
#define READ_ADDR_READY 11 //READONLY

#define READ_BITS 12 //READONLY
#define READ_VALID 13 //READONLY
#define READ_READY 14 //WRITEONLY

#endif
